name: walletika_core
description: The Walletika core library that allows to storage and connect with web3.
version: 3.5.6
homepage: https://github.com/walletika
repository: https://github.com/walletika/walletika-core
issue_tracker: https://github.com/walletika/walletika-core/issues
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  aescrypto:
    git:
      url: https://github.com/MahmoudKhalid/aescrypto-dart.git
      ref: main
  aesdatabase:
    git:
      url: https://github.com/MahmoudKhalid/aesdatabase-dart.git
      ref: main
  walletika_creator:
    git:
      url: https://github.com/Walletika/walletika-creator.git
      ref: main
  web3dart:
    git:
      url: https://github.com/MahmoudKhalid/web3dart.git
      ref: main
  http: ^0.13.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
