name: walletika_sdk
description: Software development kit of walletika.
version: 2.0.0
homepage: https://github.com/walletika
repository: https://github.com/walletika/walletika-sdk
issue_tracker: https://github.com/walletika/walletika-sdk/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  aesdatabase:
    git:
      url: https://github.com/MahmoudKhalid/aesdatabase-dart.git
      ref: main
  walletika_creator:
    git:
      url: https://github.com/Walletika/walletika-creator.git
      ref: main
  otp: ^3.1.1
  web3dart: ^2.4.1
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
